name: Terraform subnet

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credential
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=ap-northeast-1" >> $GITHUB_ENV

      - name: Initialize Terraform
        working-directory: ./terraform  
        run: terraform init
  
     
      - name: Initialize Terraform
        working-directory: ./terraform   
        run: |
          terraform apply -auto-approve
          cat outputs.tf
          terraform outputs.tf



        
      - name: Get Subnet ID
        id: subnet
        run: echo "::set-output name=subnet_id::$(terraform output -raw subnet_id)"

    #   - name: Get Security Group ID
    #     id: sg
    #     run: echo "::set-output name=security_group_id::$(terraform output -raw security_group_id)"

     
