# .github/workflows/ci-cd.yml  
name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  


    env:  
      AWS_REGION: ap-northeast-1  # 替换为您的区域

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2  

      


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registry-type: private
        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      
    #- name: Log in to Amazon ECR  
    #uses: aws-actions/amazon-ecr-login@v2  

      - name: Build and push Docker image  
        run: |  
          docker build -t my-app .  
          docker tag my-app:latest ${{ secrets.ECR_REPOSITORY_URL }}:latest  
          docker push ${{ secrets.ECR_REPOSITORY_URL }}:latest  

      - name: Deploy to ECS  
        run: |  
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
          #fef 