# .github/workflows/ci-cd.yml  
name: CI/CD Pipeline  

on:
    workflow_dispatch:
        
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run some steps for CI/CD Pipeline 
        run: echo "Running CI/CD Pipeline "


  build:
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v2  

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registry-type: private
        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

      # - name: Get ECR Repository URL
      #   id: ecr
      #   run: |
      #     ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url | awk -F '::' '{print $1}')
      #     echo "ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL" >> $GITHUB_ENV
      #   working-directory: ./terraform
      
      - name: Build and push Docker image
        # env:
        #   ECR_REPOSITORY_URL: ${{ env.ECR_REPOSITORY_URL }}  
        run: |  
          docker build -t my-app .  
          docker tag my-app:latest 822573796369.dkr.ecr.ap-northeast-1.amazonaws.com/my-app:latest
          docker push 822573796369.dkr.ecr.ap-northeast-1.amazonaws.com/my-app:latest

      - name: Deploy to ECS  
        run: |  
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment

        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Start ECS Task
        working-directory: ./terraform
        run: |
          aws ecs run-task --cluster my-cluster --launch-type FARGATE --task-definition my-task --count 1 --network-configuration "awsvpcConfiguration={subnets=['${{ steps.subnet.outputs.subnet_id }}'],securityGroups=['${{ steps.sg.outputs.security_group_id }}'],assignPublicIp=ENABLED}"  
        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          

          
# on:  
#   workflow_run:
#     workflows: ["Terraform Workflow"]
#     types:
#       - completed
