name: Terraform Workflow
#on: [push]
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=ap-northeast-1" >> $GITHUB_ENV

      - name: Clean Terraform Directory
        run: rm -rf .terraform

      - name: Initialize Terraform
        working-directory: ./terraform   
        run: terraform init

    
      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # - name: Set Static ECR Repository URL
      #   run: |
      #     echo "ECR_REPOSITORY_URL=822573796369.dkr.ecr.ap-northeast-1.amazonaws.com/my-app" >> $GITHUB_ENV 
        
    
      - name: Get Subnet ID
        id: subnet
        working-directory: ./terraform
        run: echo "subnet_id=$(terraform output -raw subnet_id)"

      - name: Get Security Group ID
        id: sg
        working-directory: ./terraform
        run: echo "security_group_id=$(terraform output -raw security_group_id)"

      - name: Debug Outputs
        run: |
          echo "Subnet ID: ${{ steps.subnet.outputs.subnet_id }}"
          echo "Security Group ID: ${{ steps.sg.outputs.security_group_id }}"

          # - name: Debug Terraform Output
      #   working-directory: ./terraform
      #   run: |
      #     set -e  
      #     ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url)  
      #     echo "ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL"  
      #     echo "ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL" >> debug_output.txt  
      #     cat debug_output.txt  
         

      # - name: Get ECR Repository URL
      #   id: ecr
      #   working-directory: ./terraform
      #   run: |
      #     ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url | awk -F '::' '{print $1}')
      #     echo "ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL"
      #     echo "ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL" >> $GITHUB_ENV

     
